Avatar DONE
SecretHouseGame/ngx-design-system pull request #95
Opened 2022-05-31 10:49 UTC by Chateneta

2022-05-31 12:21 UTC, Neerfix requested changes

2022-05-31 12:21 UTC, Neerfix commented on projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.html
> +<img src="{{link}}" alt="avatarIcon">
```suggestion
<img src="{{link}}" alt="{{avatarAlt}}">
```

2022-05-31 12:21 UTC, Neerfix commented on projects/ngx-ds-secret-house/src/lib/components/utils/avatar/avatar.component.ts
> +  @Input() link?:string;
Peut pas être nul si t'appelle le component.

-> + rajouter le avatarAlt que je t'ai review plus haut :)

2022-05-31 12:21 UTC, Neerfix commented on projects/ngx-ds-secret-house/src/lib/ngx-ds-secret-house.module.ts
> +	declarations: [NgxDsSecretHouseComponent, ...COMPONENTS, AvatarComponent],
À confirmer avec @Arty3P, mais si tu rajoute dans `const COMPONENTS` t'as pas besoin de le rajouter ici

2022-05-31 12:21 UTC, Neerfix commented on stories/utils/Avatar.stories.ts
> +  link: "https://resize.elle.fr/article/var/plain_site/storage/images/loisirs/cinema/news/avatar-2-une-premiere-bande-annonce-en-mai-4010741/96462268-1-fre-FR/Avatar-2-une-premiere-bande-annonce-en-m
- + avatarAlt

2022-06-01 15:59 UTC, Aimee-RTLNG approved these changes

2022-06-02 07:04 UTC, Neerfix approved these changes

2022-06-02 07:05 UTC, merged